### ISSUE TITLE
Failure to find source folder inside chroot

### ISSUE THREAD

**Issue by zinigor** [bobwya/build-multilib-wine#1]
First of all, thank you for such a wonderful tool! This should make my life so much easier once I get it working properly :)

Now, the problem. When I create chroots and run `build_multilib_wine.sh build-all` I get an error that I'm assuming comes from inside the chroot:

```
src_prepare () ... 
~/Wine/Source/wine ~/Wine/Source/wine
Applying patch file: "/home/zinigor/bin/Patches/wine-1.5.26-winegcc.patch" ...
Applying patch file: "/home/zinigor/bin/Patches/wine-1.6-memset-O3.patch" ...
Applying patch file: "/home/zinigor/bin/Patches/wine_winecfg_detailed_version.patch" ...
Applying patch file: "/home/zinigor/bin/Patches/wine-winhlp32-macro-flex-2.6.3-flex.patch" ...
~/Wine/Source/wine
~/Wine/Source/wine ~/Wine/Source/wine
E: Failed to change to directory ‘/home/zinigor/Wine/Source/wine’: No such file or directory
I: The directory does not exist inside the chroot.  Use the --directory option to run the command in a different directory.
build_multilib_wine.sh : schroot_session_run () : schroot -r -c "session:wine32" -d "/home/zinigor/Wine/Source/wine" -- autoreconf (session run) failed
Killed
```

I even tried binding my `$HOME` dir to chroots and `cd`-ing to `/home/zinigor/Wine/Source/wine` from inside the chroot to make sure it's there. But the script still bails with the same error.
Any idea what I can do here?

Thanks!

**Comment by bobwya** [comment]
Hiya zinigor,

First of all... Thanks for being a guinea pig for me!

Nothing is leaping out at me - straightaway!!

What I'd suggest is running:
`build_multilib_wine.sh`
to get an idea of the commands available.

Then I'd recommend generating a global configuration file:
 `build_multilib_wine.sh generate-conf`
This file will be **/etc/build_multilib_wine.conf** (unless you change the default location).
Edit this configuration file as **root** - to your liking. If you haven't done all of this already.
OK - this file really should be local to your Linux user's home folder (I'll add that to my job list!)

I presume you've run:
`build_multilib_wine.sh setup-chroot`
because otherwise the **Schroot** session wouldn't start at all!

What's the output from:
`cat /etc/schroot/chroot.d/*`
Because **Schroot** should automatically have full access to your Linux user's home directory - within the Chroot Environment.
If you try and do something "clever" - you'll probably just break the Chroot Environments!

By default the log files for the script commands are created in the directory:
`~/Wine/Build/Logs/`
It might be useful to check over these...

Bob

**Comment by zinigor** [comment]
OK, let's see:
* I have ran ` build_multilib_wine.sh` successfully and seen the help screen, that's what I was using to get myself through to the build step;
* I have generated the global conf file successfully and changed only a couple of settings there: `WINE_BRANCH` and `THREADS`.
* I have run `build_multilib_wine.sh setup-chroot`, and now I have two chroots. The problem is that the update process always terminates with this: 
```
wine_initialise
I: [wine_initialise chroot] Running command: “sh -c aptitude update	-q -y”
sh: 1: aptitude: not found
build_multilib_wine.sh : schroot_session_run () : schroot -r -c "session:wine_initialise" -d "/" -- aptitude update	-q -y (session run) failed
Killed
```
I have no idea why that is, I have been able to successfully run `aptitude` if I just `chroot` into the schroot.
* The logs that you mention say the same thing as I have pasted in the beginning, if you need to, I can attach the whole thing somewhere.

Let me know what else I can tell you.

**Comment by zinigor** [comment]
I figured it out. I have an encrypted home folder, so everything I can see inside a chroot home folder is this: 
```
Access-Your-Private-Data.desktop
.ecryptfs/
.Private/
README.txt 
```

I will have to carry the build process somewhere outside the home folder, or mount it inside the chroot.
