### ISSUE TITLE
apply_patch_array function not working

### ISSUE THREAD

**Issue by mmatis** [bobwya/build-multilib-wine#4]
Whenever the src_prepare function gets to a point where it has to run apply_patch_array, the script fails claiming it can't find a truncated version of the root path. I commented the execution of this function for the first part of the script where it applies the gentoo patches, but once it calls it again to apply the user patches, the same thing happens.

`Applying patches from patch directory: "/home/mmatis/winebuild/Patches" ...
~/winebuild/Source/wine ~
build_multilib_wine.sh : apply_patch_array () : patch file "/home/mmatis/wi" does not exist`

**Comment by bobwya** [comment]
@mmatis 

Sorry... Fixing supposed **shellcheck** issues have actually broken the script... 
Not exactly the intended purpose of this shell script testing utility... (roll-eyes)

Should have it fixed this evening...
I'm just doing a quick build test of **Wine Staging 10**+**Wine-PBA**...
Before I push a final fix to the master branch...

Thanks

**Comment by bobwya** [comment]
@mmatis 

Righteo, I think we're good to go now... Sorry 'bout my lack of testing of the script!
I'll leave the issue open for you to confirm that things are working now.

Just remember what  **dimesio** said (on the WineHQ forums) about installing the **wine** runtime libraries on the target system (i.e. the **Schroot** host). The easiest way (which I describe in the repository README) is to simply install the **winehq-staging** package on the host/ target system.

**Comment by mmatis** [comment]
Excellent! I'm going to give it a go right now!

**Comment by mmatis** [comment]
I would make enabling i386 and installing the wine runtime libs as part of the script's dependencies like schroot, or as an initial "host-prepare" step.

**Comment by bobwya** [comment]
@mmatis 

Coming out of the recent **Wineconf** in Holland...

I've been chatting with **Jens** (the Debian maintainer of Wine), he seems open to creating a simple meta-package that would _only_ pull in the runtime dependencies for Wine (and would conflict with the standard wine packages).

**Jens** also told me he is working on fixing the 32-bit/64-bit Wine dependency libraries (both runtime and buildtime), so that they can be co-installed properly. This is main / underlying issue with carrying out a multlib Wine build on **Debian** / **Ubuntu** just now. Sounds like great news!

On a related note there is a general plan to move all the WineHQ Linux packaging over to the [OpenSUSE OBS](https://build.opensuse.org/), which I think is a brilliant idea!

I'll close this Issue now... _Basically because it's bad form to piggy-back new bugs or feature requests on top of an existing ticket._ Feel free to open a seperate Issue for this feature request.
